### ISSUE TITLE
Excitometer crashes when pairing Polar H10

### ISSUE THREAD

**Issue by GeorgeFejer91** [luiseduve/exciteometer#10]
Hi there,
I tried connecting my Polar H10 device via bluetooth. It recognizes the device succesfully in step 1. In step 2 I connect to a server and tell it to record heart rate changes. It advances to step 3 and starts logging data, at which point the program suddenly stops and vanishes. What can I do to make my heartrate data discoverable by the LabRecorder via the LSL protocol?
Best,
George

**Comment by luisatheelke** [comment]
Hi George, I have a very similar problem. I've been using the repository for a bit already, but now all of a sudden it doesn't work anymore without me changing anything. Step 1 to 2 also work for me without any problems. When I start my application in Unity the data stream is there for a very short time and then suddenly stops without an error message. 
Have you by any chance found a solution?

**Comment by GeorgeFejer91** [comment]
I have asked the developers to look into it, and @luisqtr said he would double-check it over the weekend. I also tried the Android app, which in turn was actually working, and I could discover the data in the LSL stream when creating a local hotspot networking. I also tried tethering my phone directly to the Ethernet network, but for some reason the data could not be discovered by all the laptops, which a bit annoying because I am also trying to record EEG and body-posture in a multi-laptop hyperscanning setup. Hence, it would be great to have it working on a proper PC. Let's see.

**Comment by luisqtr** [comment]
Hi both,
Thanks for reporting the situation.

I looked into the video that George shared via email and it seems that you are not using the Polar **H10** but it says Polar **Pro**. 

@luisatheelke @GeorgeFejer91 Can you please confirm if you are using a sensor different to the [Polar H10](https://www.polar.com/us-en/sensors/h10-heart-rate-sensor/)? Or if you are using the Polar H10 but latest versions of the chest strap show the name as "Polar Pro"?

![image](https://user-images.githubusercontent.com/11824238/227797771-512e0770-1dc8-4541-94d1-019eb1aaada1.png)

In the code, when you search for devices and press the button "Continue", the application should automatically send you to the tab _3) Setup Polar H10_ if the BT device starts with the name `Polar H10`. Otherwise it sends you to the tab _2) Connect to server_ where you can explore the services that the Bluetooth Low Energy (BLE) device can provide. However, the data shown in the step 2 is not automatically forwarded through LSL, it is just to see if the app can actually subscribe to BLE services (the same behavior happens with the [example code](https://learn.microsoft.com/en-us/samples/microsoft/windows-universal-samples/bluetoothle/) used to build the Excite-O-Meter).

**Possible solution**: If you are not using the Polar H10, the video that George sent shows that the same app may be used to capture data from the Polar Pro. Since I don't have access to that sensor, the easiest is if I make available of the source code of the Excite-O-Meter for Windows, so that you can explore adding compatibility to the Polar Pro based on the example I built for Polar H10.

**Comment by 99bits** [comment]
Please can you provide the source code so that we can add support for other sensors. 
Thank you.

**Comment by luisqtr** [comment]
Sure. The code for the apps `Excite-O-Meter | Devices` are here:

- Android: https://github.com/luisqtr/exciteometer-devices-android
- UWP (Windows): https://github.com/luisqtr/exciteometer-devices-UWP

Please fork a repository and create a PR when you add support to more sensors so that I can push them to the main repo. 😀
