### ISSUE TITLE
can't get real data (the polar h10 has functionally worked and sent data to the Android App)

### ISSUE THREAD

**Issue by hu11ger** [luiseduve/exciteometer#15]
I have a  functionally working polar h10. Also the polar h10 successfully sends data to the Android App.
And the Android Device is in the same wifi than the PC which is running the unity project.
But the problem is: when I deactive the  the prefab EoM_SignalEmulator of the SCENE Example_withURP_NewInputSystem.unity, the INCOMING BODY SIGNALS dont show, just as the following pic shows.
Besides, I have checked the lsl panel, and it shows "No streams found!"

Again, thank you for helping me. I'm really grateful for your time!

<img width="1023" alt="image_418" src="https://github.com/luisqtr/exciteometer/assets/73094877/3b3df7f6-24fd-440c-aa84-78aac134149f">

**Comment by luisqtr** [comment]
Hi,
Usually this is a firewall problem. Some suggestions:
- Check if your local network is marked as private instead of public (as default)
- Check your Firewall restrictions and confirm that your specific Unity version has allowed inbound data
- Use the [LSL Lab Recorder](https://github.com/labstreaminglayer/App-LabRecorder) to confirm that your PC is receiving LSL data from the sensor without problems. If Lab Recorder sees your data stream, then it should be a configuration on the firewall for Unity specifically. If Lab Recorder doesn't receive stream, then it may be the network configuration as public or private.

Let me know how it goes with these steps or we can check into more details.
/Luis
